export const APPEND_DOCTORS = 'APPEND_DOCTORS';
export const DOCTOR_SEARCH = 'DOCTOR_SEARCH';
export const SELECT_DOCTOR = 'SELECT_DOCTOR';

export const TOOGLE_CONDITIONS = 'TOOGLE_CONDITIONS';
export const TOOGLE_SPECIALITIES = 'TOOGLE_SPECIALITIES';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const MERGE_SEARCH_STATE = 'MERGE_SEARCH_STATE';
