//AUTH ACTIONS
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST'
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS'
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL'
export const SUBMIT_OTP_REQUEST = 'SUBMIT_OTP_REQUEST'
export const SUBMIT_OTP_SUCCESS = 'SUBMIT_OTP_SUCCESS'
export const SUBMIT_OTP_FAIL = 'SUBMIT_OTP_FAIL'

export const APPEND_DOCTORS = 'APPEND_DOCTORS';
export const DOCTOR_SEARCH = 'DOCTOR_SEARCH';
export const SELECT_DOCTOR = 'SELECT_DOCTOR';

export const TOGGLE_CONDITIONS = 'TOGGLE_CONDITIONS';
export const TOGGLE_SPECIALITIES = 'TOGGLE_SPECIALITIES';
export const TOGGLE_TESTS = 'TOGGLE_TESTS';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const MERGE_SEARCH_STATE_OPD = 'MERGE_SEARCH_STATE_OPD';
export const TOGGLE_CRITERIA = 'TOGGLE_CRITERIA';
export const TOGGLE_DIAGNOSIS_CRITERIA = 'TOGGLE_DIAGNOSIS_CRITERIA';
export const SET_OPD_FILTERS = 'SET_OPD_FILTERS'
export const SET_LABS_FILTERS = 'SET_LABS_FILTERS'
export const LOAD_SEARCH_CRITERIA_OPD = 'LOAD_SEARCH_CRITERIA_OPD'

export const MERGE_SEARCH_STATE_LAB = 'MERGE_SEARCH_STATE_LAB';
export const LOAD_SEARCH_CRITERIA_LAB = 'LOAD_SEARCH_CRITERIA_OPD'
export const APPEND_LABS = 'APPEND_LABS';
export const LAB_SEARCH = 'LAB_SEARCH';
export const SELECT_LOCATION_DIAGNOSIS = 'SELECT_LOCATION_DIAGNOSIS';
export const APPEND_FILTERS_DIAGNOSIS = 'APPEND_FILTERS_DIAGNOSIS';
export const LAB_SEARCH_START = 'LAB_SEARCH_START';


export const APPEND_USER_PROFILES = 'APPEND_USER_PROFILES';
